services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aklamio
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aklamio
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    command: ["python", "main.py", "stream"]  # Change "batch" to "stream" if needed

volumes:
  pg_data:
